services:
  db:
    image: pgvector/pgvector:pg16
    container_name: dongunet_pgvector
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ecomatch
      POSTGRES_USER: ecomatch
      POSTGRES_PASSWORD: 1Eco2Meko3Seko
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata: