
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS facilities CASCADE;
DROP TABLE IF EXISTS osbs CASCADE;
DROP TABLE IF EXISTS _prisma_migrations CASCADE;

DROP TYPE IF EXISTS "UserRole";
DROP TYPE IF EXISTS "MatchStatus";
DROP TYPE IF EXISTS "RecordType";
